const inappropriateWords = [
    'ahmak',
    'mal',
    'aptal',
    'salak',
    'gerizekalı',
    'amcık',
    'sik',
    'orospu',
    'orospu çocuğu',
    'göt',
    'siktir',
    'ibne',
    'pezevenk',
    'yarrak',
    'piç',
    'gavat',
    'kaltak',
    'goyim',
    'nazi',
    'faşist',
    'ırkçı',
    'homofobik',
    'zoofili',
    'pedofili',
    'anüs',
    'anal',
    'meme',
    'göğsü',
    'porno',
    'seks',
    'mastürbasyon',
    'uyuşturucu',
    'alkol',
    'hırsız',
    'soyguncu',
    'katil',
    'intihar',
    'öldürmek',
    'kan',
    'şiddet',
    'tecavüz',
    'cinsel saldırı',
    'kadın tacizi',
    'erkek tacizi',
    'zina',
    'aldatmak',
    'yolsuzluk',
    'rüşvet',
    'küfür',
    'küfürlü',
    'küfürlü konuşma',
    'küfürlü dil',
    'uyuşturucu bağımlısı',
    'alkolik',
    'esrar',
    'kokain',
    'eroin',
    'uyuşturucu kullanımı',
    'alkol bağımlılığı',
    'tecavüzcü',
    'cinsel istismar',
    'çocuk istismarı',
    'pedofili',
    'zoofili',
    'necrophilia',
    'intihar etmek',
    'intihar düşüncesi',
    'şiddet içeren',
    'şiddet dolu',
    'silah kullanımı',
    'radikal',
    'terörist',
    'bombalama',
    'hırsızlık',
    'soygun',
    'kanlı',
    'cinayet',
    'suikast',
    'ajan',
    'casusluk',
    'ırk ayrımcılığı',
    'homofobi',
    'transfobi',
    'xenofobi',
    'antisemitizm',
    'negatif',
    'zararlı',
    'tehdit',
    'kaos',
    'anarşi',
    'küfürlü konuşma',
    'taciz',
    'aşağılama',
    'kandırmak',
    'dolandırıcılık',
    'yalan',
    'yalan söylemek',
    'iftira',
    'çalıntı',
    'sahtecilik',
    'spam',
    'virüs',
    'malware',
    'phishing',
    'hack',
    'siber saldırı',
];

export default inappropriateWords;
